name: "Build"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ocamlVersion: [4_07, 4_08, 4_09, 4_10, 4_11]
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v9
      with:
        skip_adding_nixpkgs_channel: true
    - uses: cachix/cachix-action@v6
      with:
        name: anmonteiro
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: "Run nix-build"
      run: nix-build ./nix/ci/test.nix --argstr ocamlVersion ${{ matrix.ocamlVersion }}
