name: "Build"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ocamlVersion: [4_12, 4_13, 4_14, 5_00]
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
      - uses: cachix/cachix-action@v10
        with:
          name: anmonteiro
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: "Run nix-build"
        run: nix-build ./nix/ci/test.nix --argstr ocamlVersion ${{ matrix.ocamlVersion }}
